export const ActionTypes = {
    LOGIN_USER: 'LOGIN_USER',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
    GET_CURRENT_CONTACT: 'GET_CURRENT_CONTACT',
    GET_CURRENT_CONTACT_SUCCESS: 'GET_CURRENT_CONTACT_SUCCESS',
    GET_CURRENT_CONTACT_FAILURE: 'GET_CURRENT_CONTACT_FAILURE',
    GET_MESSAGES: 'GET_MESSAGES',
    GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
    GET_MESSAGES_FAILURE: 'GET_MESSAGES_FAILURE',
}